shellEmulator: true

trustPolicy: no-downgrade

packages:
  - 'backend/packages/*'
  - 'backend/stages/*'
  - 'backend/projects/*'
  - 'backend/apps/*'
  - frontend
overrides:
  eslint-flat-config-utils: 3.0.2
